apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-service
spec:
  selector:
    matchLabels:
      app: backend-service
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: backend-service
    spec:
      containers:
        - name: backend-service
          image: {regisytry-id}/{image-name}:{tag}
          env:
            - name: REDIS_HOST
              value: redis
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
spec:
  selector:
    matchLabels:
      app: redis-server
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: redis-server
    spec:
      containers:
        - name: redis-server
          image: redis



